# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Category')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Enterprise')),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Merch')),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='merch',
            field=models.ManyToManyField(through='orgs.Merchandise', to='orgs.Enterprise'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='affiliation',
            field=models.ManyToManyField(to='orgs.EnterpriseNetwork'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='district',
            field=models.ManyToManyField(to='orgs.District'),
        ),
    ]
